### ISSUE TITLE
Remote HVAC help

### ISSUE THREAD

**Issue by finalbillybong** [SAIC-iSmart-API/saic-home-assistant-addon#126]
I am really struggling to get the HVAC to start remotly on my MG4. I am using MQTT and sending the command:

```
action: mqtt.publish
data:
  evaluate_payload: false
  qos: 0
  retain: false
  topic: >-
    saic/email-redacted/vehicles/vin-number-redacted/climate/remoteClimateState
  payload: "on"
```

Which results in a state change of:

```
saic/email-redacted/vehicles/vin-number-redacted/climate/remoteClimateState
```
to 'on'.

Yet the climate in the car never switches on. 

What am I doing wrong?
